[build]
  command = "yarn build"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "remix watch"
  port = 9000

[functions.server]
  included_files = ["app/routes/**/*.mdx", "app/data/members/*.js", "app/data/members/core/*.js", "app/data/members/members/*.js"]

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[redirects]]
  from = "/netlify-forms"
  to = "/"
  status = 200

[[redirects]]
  from = "/report-coc-violation-success"
  to = "/"
  status = 200

[[redirects]]
  from = "/sponsorship"
  to = "https://github.com/sponsors/Virtual-Coffee"
  status = 302

[[redirects]]
  from = "/membership"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/membership/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/brownbag-idea"
  to = "/lunch-and-learn-idea"
  status = 301
  force = true

[[redirects]]
  from = "/brownbag-idea-thanks"
  to = "/lunch-and-learn-idea-thanks"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources"
  to = "/resources"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources/oss-maintainer-checklist"
  to = "/resources/open-source/oss-maintainer-checklist"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources/oss-writing-issues"
  to = "/resources/open-source/oss-writing-issues"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources/guide-to-vc"
  to = "/resources/virtual-coffee/guide-to-vc"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources/join-virtual-coffee"
  to = "/resources/virtual-coffee/join-virtual-coffee"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources/slack-channel-guide"
  to = "/resources/virtual-coffee/slack-channel-guide"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200