[build]
  publish = "_site"
  command = "yarn build"
  functions = "functions"

[dev]
  publish = "_site"
  command = "yarn start"
  framework = "#custom"
  targetPort = 9000

[[redirects]]
  from = "/membership"
  to = "/"
  status = 301
  force = true