[build]
  publish = "_site"
  command = "yarn build"

[dev]
  publish = "_site"
  command = "yarn start"
  framework = "#custom"
  targetPort = 9000

[[redirects]]
  from = "/membership"
  to = "/"
  status = 301
  force = true

  [[redirects]]
  from = "/brownbag-idea"
  to = "/lunch-and-learn-idea"
  status = 301
  force = true

  [[redirects]]
  from = "/brownbag-idea-thanks"
  to = "/lunch-and-learn-idea-thanks"
  status = 301
  force = true