blank_issues_enabled: true
contact_links:
  - name: '❓  Questions/Ideas/Feedback'
    url: 'https://github.com/Virtual-Coffee/virtualcoffee.io/discussions'
    about: 'Please use our Discussion Board for any open-ended questions or other discussion ❤️'
