# This is a basic workflow to help you get started with Actions

name: Netlify Build
on:
  workflow_dispatch:
  schedule:
    # Run at 0815 daily
    - cron: '15 8 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    if: github.repository == 'Virtual-Coffee/virtualcoffee.io'
    steps:
      - name: Curl request
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: curl -X POST -d {} "$NETLIFY_BUILD_HOOK"
