name: Formatting PR with Prettier
on:
  pull_request_target:
    branches:
      - 'main'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn format
      - name: Using Prettier to format code
        uses: creyD/prettier_action@v4.2
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
